### ISSUE TITLE
SPIKE: generate dessert recipe

### ISSUE THREAD

**Issue by tien-chung** [CookingLab/cooking-lab#48]
As a user, I want to be able to generate dessert recipe, so I can make a dessert if that is what I desire.

- [x] Research if it's possible to filter out dessert recipes only on Edamam api
- [x] Get the request url
- [x] Create a FEAT story to add dessert recipe if this spike is successful

**Comment by ThiiLuu79** [comment]
@tien-chung Edamam has a parameter **dishType** : https://developer.edamam.com/edamam-docs-recipe-api


This can be added as an optional param to the url to add a dessert filter.

The problem is that a lunch and a dinner can return a dessert. Is this concerning? If not, we can proceed to the implementation of this feature.

![Image](https://github.com/user-attachments/assets/71bbe5d5-6c72-4dad-996a-37ee2d4aafda)

**Comment by tien-chung** [comment]
@ThiiLuu79 I think we should be okay to proceed.
